;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	))

(setq mc/cmds-to-run-once
      '(
	View-scroll-page-backward
	beginning-of-buffer
	counsel-find-file
	end-of-buffer
	help-for-help
	ns-copy-including-secondary
	win-switch-dispatch
	))
